import type { Metadata } from "next";
import { firaSans } from "@/app/ui/fonts";
import '@/app/ui/globals.css';
import { Analytics } from "@vercel/analytics/react"


import Footer from "@/app/ui/components/footer";
import "@/app/lib/fontawesome";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;


export const metadata: Metadata = {
  title: "Mitch Duffy's Professional Site",
  description: "Generated by create next app",
  icons: {
    icon: '/user-astronaut-solid.svg',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${firaSans.variable} --font-fira-sans antialiased`}>
        {children}
        <Analytics />
        <Footer />
      </body>
    </html>
  );
}
