import type { Metadata } from "next";
import { firaMono, firaSans, firaCode } from "@/app/ui/fonts";
import "@/app/ui/globals.css";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

import Footer from "@/app/ui/components/footer";
import "@/app/lib/fontawesome";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Mitch Duffy's Professional Site",
  description: "Generated by create next app",
  icons: {
    icon: "/user-astronaut-solid.svg",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaSans.className} ${firaSans.variable} ${firaCode.variable} ${firaMono.variable} antialiased`}
      >
        {children}
        <Analytics />
        <SpeedInsights />
        <Footer />
      </body>
    </html>
  );
}
