import type { Metadata } from "next";
// import { montserrat } from "@/app/ui/fonts";
import '@/app/ui/globals.css';
import "@/app/lib/fontawesome"; // ✅ Import the icons setup
import "@fortawesome/fontawesome-svg-core/styles.css"; // ✅ Required to load icons properly
import { config } from "@fortawesome/fontawesome-svg-core";
import SideNav from "@/app/ui/components/portfolio/sidenav";
config.autoAddCss = false;


export const metadata: Metadata = {
    title: "Mitch Duffy",
    description: "Generated by create next app",
    icons: {
        icon: '/user-astronaut-solid.svg',
    }
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <div className="w-full flex-none md:w-64">
                HIIT This Fitness WOOOOOOO!!!
                <SideNav />
            </div>
            <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
        </div>
    );
}
